name: Bug report
description: Create a report to help improve this package.
title: "[BUG]"
labels:
  - bug
body:
  - type: input
    id: renovate-version
    attributes:
      label: Renovate version
      description: Which Renovate version are you using?
      placeholder: 'e.g. 36.99'
    validations:
      required: true
  - type: checkboxes
    id: presets
    attributes:
      label: Presets
      description: Which presets are you using?
      options:
        - label: default
        - label: git-flow
        - label: typo3-extension
        - label: typo3-project
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: What version of this package are you using?
      placeholder: 'e.g. 1.0.0'
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: platform
      description: On which platform did the error occur?
      options:
        - GitHub
        - GitLab
        - Something else (please describe below)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If possible, describe steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
